apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: zipkin
          urlDisplayLabel: View in Zipkin

  - name: Zipkin
    type: zipkin
    uid: zipkin
    url: http://zipkin:9411
    access: proxy
    isDefault: false
    editable: false
